default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_app_development

test:
  <<: *default
  database: hello_app_test

production:
  <<: *default
  url: <%= ENV["MY_APP_DATABASE_URL"] %>
  DATABASE_URL: 'postgres://mysite:nveSDddI4h2VbNsWyu2SMMdm2xDk1ZkR@dpg-cocnrtq0si5c73ambhog-a/mysite_k1pn'
  database: mysite_k1pn
  username: mysite
  password: <%= ENV["HELLO_APP_DATABASE_PASSWORD"] %>